// <auto-generated />
using System;
using EventFlow.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EventFlow.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(EventFlowDbContext))]
    partial class EventFlowDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EventFlow.Domain.Entities.Evento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Capacidade")
                        .HasColumnType("integer")
                        .HasColumnName("capacidade");

                    b.Property<DateTimeOffset>("DataHoraFim")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_hora_fim");

                    b.Property<DateTimeOffset>("DataHoraInicio")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_hora_inicio");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("descricao");

                    b.Property<string>("Local")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("local");

                    b.Property<decimal>("Preco")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("preco");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("titulo");

                    b.HasKey("Id");

                    b.ToTable("eventos", (string)null);
                });

            modelBuilder.Entity("EventFlow.Domain.Entities.Inscricao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("DataInscricao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_inscricao");

                    b.Property<Guid>("EventoId")
                        .HasColumnType("uuid")
                        .HasColumnName("evento_id");

                    b.Property<string>("QrCode")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("qr_code");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.HasIndex("EventoId", "UsuarioId")
                        .IsUnique();

                    b.ToTable("inscricoes", (string)null);
                });

            modelBuilder.Entity("EventFlow.Domain.Entities.MidiaEvento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Alt")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("alt");

                    b.Property<bool>("Destaque")
                        .HasColumnType("boolean")
                        .HasColumnName("destaque");

                    b.Property<int>("Ordem")
                        .HasColumnType("integer")
                        .HasColumnName("ordem");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer")
                        .HasColumnName("tipo");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("url");

                    b.Property<Guid>("evento_id")
                        .HasColumnType("uuid")
                        .HasColumnName("evento_id");

                    b.HasKey("Id");

                    b.HasIndex("evento_id");

                    b.ToTable("evento_midias", (string)null);
                });

            modelBuilder.Entity("EventFlow.Domain.Entities.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("email");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nome");

                    b.Property<int>("Papel")
                        .HasColumnType("integer")
                        .HasColumnName("papel");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("senha_hash");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("usuarios", (string)null);
                });

            modelBuilder.Entity("EventFlow.Domain.Entities.Inscricao", b =>
                {
                    b.HasOne("EventFlow.Domain.Entities.Evento", null)
                        .WithMany()
                        .HasForeignKey("EventoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EventFlow.Domain.Entities.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("EventFlow.Domain.Entities.MidiaEvento", b =>
                {
                    b.HasOne("EventFlow.Domain.Entities.Evento", null)
                        .WithMany("Midias")
                        .HasForeignKey("evento_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EventFlow.Domain.Entities.Evento", b =>
                {
                    b.Navigation("Midias");
                });
#pragma warning restore 612, 618
        }
    }
}
